name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Or your default branch
  pull_request:
    branches:
      - main  # Or your default branch

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'  # Adjust Go version accordingly

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Install dependencies
        run: |
          go mod tidy
          go get -v

      - name: Run tests
        run: go test -v -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}

      - name: Upload code coverage to SonarCloud
        run: |
          curl -u $SONAR_TOKEN: -X POST \
          -d "coverage=$(cat coverage.out)" \
          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=<your_project_key>"
